version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: putrawitama/php-ci
    container_name: resto-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: resto-app-php
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker-settings/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - resto-app-php-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: resto-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8082:80"
      - "442:443"
    volumes:
      - ./:/var/www
      - ./docker-settings/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - resto-app-php-network

  #MySQL Service
  db:
    image: mysql:5.7
    container_name: resto-db
    restart: unless-stopped
    tty: true
    ports:
      - "33062:3306"
    environment:
      MYSQL_DATABASE: pesan_makanan
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker-settings/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - resto-app-php-network

#Docker Networks
networks:
  resto-app-php-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local